@FindMeABarber_HostAddress = https://localhost:7043

GET {{FindMeABarber_HostAddress}}/barbers
Content-Type: application/json
Accept: application/json

###


GET {{FindMeABarber_HostAddress}}/barbers/1
Content-Type: application/json
Accept: application/json

###


POST {{FindMeABarber_HostAddress}}/barbers
Content-Type: application/json
Accept: application/json
{
    "barberid": 1,
    "barbername": "John",
    "barbersurname": "Doe",
    "barberage": 30,
    "barberaddress": "123 Main St",
    "barbermobilenumber": "555-1234"
}


###

DELETE {{FindMeABarber_HostAddress}}/barbers/1
Content-Type: application/json
Accept: application/json

###