@FindMeABarber_HostAddress = http://localhost:5092

GET {{FindMeABarber_HostAddress}}/barbers
Content-Type: application/json
Accept: application/json

###


GET {{FindMeABarber_HostAddress}}/barbers/1
Content-Type: application/json
Accept: application/json

###


POST {{FindMeABarber_HostAddress}}/barbers
Content-Type: application/json
Accept: application/json
{    
    "barbername": "pepe",
    "barbersurname": "palotes",
    "barberage": 29,
    "barberaddress": "28a keymer road",
    "barbermobilenumber": "555-444448888"
}


###

DELETE {{FindMeABarber_HostAddress}}/barbers/1
Content-Type: application/json
Accept: application/json

###